/* =====================================================================
   FACE-OFF: A+ CORE 2  —  ACRONYM POOL
   Exam: CompTIA A+ 220-1202
   ---------------------------------------------------------------------
   GENERATED FILE — do not hand-edit.
   Rebuild with:  python3 tools/build-acronyms.py
   Source of truth: the A+ CORE 2 acronym repo's data/acronyms.json.

   202 acronyms in 15 categories.

   THERE IS NO DIFFICULTY RAMP IN AN ACRONYM. Nothing makes MAC a 100
   and SD-WAN a 500, which is a problem on a board whose whole shape is
   a column climbing 100 to 500. So the ramp is the TASK, not the item:
   the cheap rows ask you to expand the letters, the middle rows give
   you a description and ask which acronym it is, and the dear rows
   give you the acronym and ask what it actually does. Same acronym,
   three difficulties — which is also why 202 acronyms go a long way.

   The clue text is built at draw time from these three fields, so
   there is no answer bank to memorise and editing an acronym here
   changes every form of it at once.

     ac = the acronym          ex = what the letters stand for
     df = what it actually does
     amb = set only when this acronym means something else somewhere
           in the bank; the clue names this field so the team is not
           marked wrong for giving the other correct expansion.

   Categories with fewer than 5 entries cannot fill a five-row column
   and are skipped on the largest boards. They still play on shorter
   boards and in the Lightning Final. Currently: PRINTERS.
   ===================================================================== */

window.FACEOFF_ACRONYMS = {
  categories: [
    { name: "PROCESSORS, MEMORY & BOARDS",
      items: [
      { ac: "AMD",
        ex: "Advanced Micro Devices, Inc.",
        df: "Hardware maker of PC processors and graphics chips used in desktops and laptops." },
      { ac: "ARM",
        ex: "Advanced RISC [Reduced Instruction Set Computer] Machine",
        df: "CPU architecture optimized for low power; common in phones, tablets, and some laptops." },
      { ac: "ATX",
        ex: "Advanced Technology Extended",
        df: "Motherboard and power-supply form factor standard that defines size, mounting, and connectors." },
      { ac: "BIOS",
        ex: "Basic Input/Output System",
        df: "Firmware that initializes hardware and starts the boot process on older PCs (superseded by UEFI on newer systems)." },
      { ac: "CAS",
        ex: "Column Address Strobe",
        df: "Signal used by RAM to locate and access a specific column of data. It works with RAS (Row Address Strobe) to identify exact memory locations. CAS latency (CL) is a key performance metric lower is faster." },
      { ac: "CMOS",
        ex: "Complementary Metal-Oxide Semiconductor",
        df: "Battery-backed chip that stores BIOS/UEFI settings and maintains the real-time clock." },
      { ac: "CPU",
        ex: "Central Processing Unit",
        df: "The central processor that performs calculations and runs instructions for the system." },
      { ac: "DDR",
        ex: "Double Data Rate",
        df: "Type of synchronous DRAM that transfers data on both clock edges; used as main system memory." },
      { ac: "DIMM",
        ex: "Dual In-line Memory Module",
        df: "Removable memory module that plugs into motherboard slots to add RAM." },
      { ac: "ECC",
        ex: "Error-correcting Code",
        df: "Error-correcting Code memory that adds extra bits so the system can detect and correct single-bit errors, used for higher reliability (often in servers)." },
      { ac: "GPU",
        ex: "Graphics Processing Unit",
        df: "Graphics Processing Unit, processor specialized for rendering graphics and accelerating parallel workloads (e.g., video, AI)." },
      { ac: "ITX",
        ex: "Information Technology eXtended",
        df: "Information Technology eXtended, small motherboard form-factor family (e.g., Mini-ITX) used in compact PC builds." },
      { ac: "OEM",
        ex: "Original Equipment Manufacturer",
        df: "Company that produces hardware or software that is sold under another company's brand. In IT, OEM licenses are tied to specific hardware (like Windows preinstalled on a PC)." },
      { ac: "PC",
        ex: "Personal Computer",
        df: "Personal Computer, a general-purpose computing device for a single user." },
      { ac: "PCI",
        ex: "Peripheral Component Interconnect",
        df: "Peripheral Component Interconnect, older expansion bus used for add-in cards inside PCs." },
      { ac: "PCIe",
        ex: "Peripheral Component Interconnect Express",
        df: "Peripheral Component Interconnect Express, modern high-speed serial bus used for GPUs, NVMe SSDs, and other cards." },
      { ac: "POST",
        ex: "Power-on Self-test",
        df: "Power-On Self-Test, firmware diagnostics that check hardware components during system startup." },
      { ac: "RAM",
        ex: "Random-access Memory",
        df: "Random Access Memory, short-term working memory that stores active programs and data for quick CPU access; cleared when power is off." },
      { ac: "RISC",
        ex: "Reduced Instruction Set Computer",
        df: "Reduced Instruction Set Computer, CPU architecture using a small set of simple instructions for efficient, high-speed processing used in smartphones, tablets, smartwatches, and embedded systems." },
      { ac: "SODIMM",
        ex: "Small Outline Dual In-line Memory Module",
        df: "A compact type of RAM module used mainly in laptops, small-form-factor PCs, and some all-in-one systems." },
      { ac: "UEFI",
        ex: "Unified Extensible Firmware Interface",
        df: "Modern PC firmware that initializes hardware and boots the OS; supports larger disks, faster boot, Secure Boot, and a graphical setup." },
      { ac: "VRAM",
        ex: "Video Random-access Memory",
        df: "A type of memory used by a computer's graphics card to store image and video data for display rendering." },
      ] },
    { name: "INTERNET & REMOTE ACCESS",
      items: [
      { ac: "DSL",
        ex: "Digital Subscriber Line",
        df: "Internet service that uses telephone lines to provide broadband connectivity." },
      { ac: "FTP",
        ex: "File Transfer Protocol",
        df: "File Transfer Protocol, legacy file transfer protocol (TCP/21) that sends data in clear text; prefer SFTP/FTPS for security." },
      { ac: "HTTP",
        ex: "Hypertext Transfer Protocol",
        df: "Hypertext Transfer Protocol, the basic web protocol (TCP/80) used for transferring web pages and APIs without encryption." },
      { ac: "HTTPS",
        ex: "Hypertext Transfer Protocol Secure",
        df: "HTTP Secure, HTTP over TLS/SSL (TCP/443) that encrypts and authenticates web traffic to protect data in transit." },
      { ac: "IMAP",
        ex: "Internet Mail Access Protocol",
        df: "Internet Message Access Protocol, email protocol (TCP/143; SSL/TLS 993) that keeps mail on the server and syncs across devices." },
      { ac: "ISP",
        ex: "Internet Service Provider",
        df: "Company that provides internet access to users. Examples include Comcast, AT&T, and Spectrum. They connect your home or business network to the internet." },
      { ac: "LDAP",
        ex: "Lightweight Directory Access Protocol",
        df: "A network protocol for querying and managing directory services (users, groups, permissions) such as Active Directory." },
      { ac: "ONT",
        ex: "Optical Network Termina",
        df: "Optical Network Terminal, carrier device that converts fiber signals to Ethernet at the customer premises." },
      { ac: "POP",
        ex: "Post Office Protocol",
        df: "Post Office Protocol (POP3), email retrieval protocol that typically downloads messages to the client." },
      { ac: "PXE",
        ex: "Preboot eXecution Environment",
        df: "Preboot eXecution Environment, boots a computer from the network to deploy images or run installers." },
      { ac: "RDP",
        ex: "Remote Desktop Protocol",
        df: "Remote Desktop Protocol, allows a user to remotely log in to and control a Windows computer over the network." },
      { ac: "RMM",
        ex: "Remote Monitoring and Management",
        df: "Software used by IT administrators or Managed Service Providers (MSPs) to remotely monitor, maintain, and manage clients' computers, servers, and networks." },
      { ac: "SFTP",
        ex: "Secure File Transfer Protocol",
        df: "SSH File Transfer Protocol, secure file transfer protocol that runs over SSH for encrypted uploads/downloads." },
      { ac: "SMTP",
        ex: "Simple Mail Transfer Protocol",
        df: "Simple Mail Transfer Protocol, protocol used to send outbound email from clients/servers." },
      { ac: "SNMP",
        ex: "Simple Network Management Protocol",
        df: "Protocol used to monitor and manage network devices (routers, switches, servers). It collects data like performance metrics, errors, and device status." },
      { ac: "SPICE",
        ex: "Simple Protocol for Independent Computing Environments (1202)",
        amb: "INTERNET & REMOTE ACCESS",
        df: "A remote-display protocol that delivers virtual desktops and applications from servers to client devices, commonly used with virtualization platforms like KVM." },
      { ac: "SSH",
        ex: "Secure Shell",
        df: "Secure Shell, encrypted remote login and command execution protocol for administering systems." },
      { ac: "UPnP",
        ex: "Universal Plug and Play",
        df: "Network protocol that lets devices auto-discover and request port forwarding on a router; convenient but can be a security risk if left enabled on internet-facing networks." },
      { ac: "VNC",
        ex: "Virtual Network Computer (Computing?)",
        df: "Remote-desktop protocol that shares a graphical desktop over the network for control and support." },
      { ac: "VoIP",
        ex: "Voice over Internet Protocol",
        df: "Technology that carries phone calls over IP networks instead of traditional phone lines." },
      { ac: "VPN",
        ex: "Virtual Private Network",
        df: "A secure network connection that encrypts internet traffic and allows private communication over public networks." },
      { ac: "WinRM",
        ex: "Windows Remote Management",
        df: "Microsoft's remote-management service using WS-Management; enables PowerShell remoting over HTTP/HTTPS (default ports 5985/5986)." },
      ] },
    { name: "NETWORK FUNDAMENTALS",
      items: [
      { ac: "APIPA",
        ex: "Automatic Private Internet Protocol Addressing",
        df: "Windows feature that self-assigns a 169.254.x.x address when DHCP is unavailable." },
      { ac: "CNAME",
        ex: "Canonical Name",
        df: "DNS record that creates an alias from one hostname to another (canonical) name." },
      { ac: "DHCP",
        ex: "Dynamic Host Configuration Protocol",
        df: "Service that automatically assigns IP addresses and network settings to clients." },
      { ac: "DNS",
        ex: "Domain Name System",
        df: "System that translates human-readable domain names into IP addresses." },
      { ac: "IP",
        ex: "Internet Protocol",
        df: "Internet Protocol, the addressing and routing system (IPv4/IPv6) that delivers packets across networks." },
      { ac: "LAN",
        ex: "Local Area Network",
        df: "A local network that connects computers and devices within a small area (home, office, school) for sharing data and resources." },
      { ac: "MAC",
        ex: "Media Access Control",
        df: "A unique hardware address assigned to a network interface used for Layer 2 communication on a LAN." },
      { ac: "MAN",
        ex: "Metropolitan Area Network",
        df: "A network that spans a city or campus area, larger than a LAN but smaller than a WAN." },
      { ac: "MX",
        ex: "Mail Exchange",
        df: "A DNS record type that specifies which mail servers accept email for a domain." },
      { ac: "NAT",
        ex: "Network Address Translation",
        df: "Method used by routers to translate private IP addresses into a public IP address so devices on a local network can access the internet. Helps conserve IP addresses and adds a layer of security" },
      { ac: "NetBIOS",
        ex: "Network Basic Input/Output System",
        df: "Legacy Windows networking API/protocol suite for name services and sessions within a LAN." },
      { ac: "NIC",
        ex: "Network Interface Card",
        df: "Network Interface Card/Controller, the hardware that connects a computer to a network (wired or wireless)." },
      { ac: "NTP",
        ex: "Network Time Protocol",
        df: "Network Time Protocol, keeps computer clocks synchronized over a network." },
      { ac: "PAN",
        ex: "Personal Area Network",
        df: "Personal Area Network, short-range network for personal devices like phones, headsets, and wearables." },
      { ac: "QoS",
        ex: "Quality of Service",
        df: "Quality of Service, manages and prioritizes network traffic to improve performance for critical applications (e.g., VoIP/video)." },
      { ac: "SOHO",
        ex: "Small Office/Home Office",
        df: "Small Office/Home Office, refers to small-scale business/home networks and equipment." },
      { ac: "TCP",
        ex: "Transmission Control Protocol",
        df: "A core protocol in the Internet Protocol Suite that ensures reliable, ordered, and error-checked delivery of data between applications." },
      { ac: "TXT",
        ex: "Text",
        df: "Plain-text file format/extension with no special formatting. Also in DNS, a TXT record stores arbitrary text like SPF/DMARC data." },
      { ac: "UDP",
        ex: "User Datagram Protocol",
        df: "A transport layer protocol that sends data without connection setup or delivery guarantees, used for streaming and gaming." },
      { ac: "VLAN",
        ex: "Virtual LAN [Local Area Network]",
        df: "Logically segments a switch/network into separate broadcast domains for isolation and better performance without extra physical switches." },
      { ac: "WAN",
        ex: "Wide Area Network",
        df: "A wide area network that connects computers and networks over large geographic distances, such as the internet." },
      ] },
    { name: "POLICY, SAFETY & OPERATIONS",
      items: [
      { ac: "AUP",
        ex: "Acceptable Use Policy",
        df: "Policy that sets rules for acceptable use of an organization's computers, network, and Internet access." },
      { ac: "CMDB",
        ex: "Configuration Management Database",
        df: "Repository that tracks IT assets, configurations, and their relationships to support change/incident management." },
      { ac: "EOL",
        ex: "End-of-life",
        df: "End-of-Life, when a vendor stops updates and support for a product; using EOL gear increases security and reliability risk." },
      { ac: "ESD",
        ex: "Electrostatic Discharge",
        df: "Electrostatic Discharge, static electricity that can damage components; controlled with wrist straps, mats, and proper handling." },
      { ac: "EULA",
        ex: "End-user License Agreement",
        df: "End-User License Agreement, the legal terms that define how you may install and use software." },
      { ac: "GFS",
        ex: "Grandfather-Father-Son",
        df: "Grandfather-Father-Son, a backup rotation scheme using daily (son), weekly (father), and monthly (grandfather) backup sets." },
      { ac: "IoT",
        ex: "Internet of Things",
        df: "Internet of Things, networked devices (sensors, appliances, cameras) that collect and exchange data; often require strong security." },
      { ac: "ISO",
        ex: "International Organization for Standardization",
        df: "International Organization for Standardization, develops global standards; in IT you'll also see \"ISO image,\" a single-file copy of an optical disc." },
      { ac: "MNDA",
        ex: "Mutual Non-disclosure Agreement",
        df: "Mutual Non-Disclosure Agreement, both parties agree to keep shared confidential information private." },
      { ac: "MSDS",
        ex: "Material Safety Data Sheet",
        df: "Material Safety Data Sheet (now SDS), explains hazards and safe handling of chemicals like toner or cleaners." },
      { ac: "NDA",
        ex: "Non-disclosure Agreement",
        df: "Non-Disclosure Agreement, a legal contract to keep specified information confidential." },
      { ac: "PII",
        ex: "Personally Identifiable Information",
        df: "Personally Identifiable Information, data that can identify a person (e.g., name + SSN, address, DOB)." },
      { ac: "PSU",
        ex: "Power Supply Unit",
        df: "Power Supply Unit, converts AC wall power to regulated DC voltages for PC components." },
      { ac: "RSR",
        ex: "Rapid Security Response",
        df: "An urgent security update, typically released outside normal patch cycles, to fix newly discovered vulnerabilities or active threats quickly." },
      { ac: "SCADA",
        ex: "Supervisory Control and Data Acquisition",
        df: "A system used to monitor and control industrial processes such as utilities, manufacturing, and energy infrastructure." },
      { ac: "SLA",
        ex: "Service-level Agreement",
        df: "A formal contract between a service provider and customer that defines performance expectations, uptime guarantees, and response times." },
      { ac: "SOP",
        ex: "Standard Operating Procedure",
        df: "A documented set of step-by-step instructions that outlines how to perform routine tasks consistently and safely within an organization." },
      { ac: "SPICE",
        ex: "Software Process Improvement and Capability Determination (1201)",
        amb: "POLICY, SAFETY & OPERATIONS",
        df: "A framework (ISO/IEC 15504) used to assess and improve software development processes within organizations." },
      { ac: "UPS",
        ex: "Uninterruptible Power Supply",
        df: "A backup power device that supplies electricity to computers or equipment during short power outages or fluctuations." },
      ] },
    { name: "STORAGE",
      items: [
      { ac: "eSATA",
        ex: "External Serial Advanced Technology Attachment",
        df: "External Serial ATA, an external connector for SATA storage that provides fast, direct-attach disk performance (largely replaced by USB 3.x/USB-C)." },
      { ac: "GPT",
        ex: "GUID [Globally Unique Identifier] Partition Table",
        df: "GUID Partition Table, modern disk partitioning standard that supports >2 TB drives and many partitions; required by UEFI systems." },
      { ac: "HDD",
        ex: "Hard Disk Drive",
        df: "Hard Disk Drive, magnetic spinning-platter storage offering large capacity at low cost but slower than SSDs and more shock-sensitive." },
      { ac: "IOPS",
        ex: "Input/Output Operations Per Second",
        df: "Input/Output Operations Per Second, storage performance metric indicating how many reads/writes a device can handle each second." },
      { ac: "MBR",
        ex: "Master Boot Record",
        df: "Legacy disk partitioning and boot sector format used by BIOS systems; stores the bootloader and partition table." },
      { ac: "mSATA",
        ex: "Mini-serial Advanced Technology Attachment",
        df: "A compact SATA-based SSD form factor used in small devices and older laptops; connects via SATA interface." },
      { ac: "NAS",
        ex: "Network Attached Storage",
        df: "Dedicated storage device connected to a network that allows multiple users/devices to store and access files centrally. Common in homes and businesses for file sharing and backups" },
      { ac: "NVMe",
        ex: "Non-volatile Memory Express",
        df: "High-performance storage protocol for SSDs that uses PCIe lanes for very fast reads/writes." },
      { ac: "RAID",
        ex: "Redundant Array of Independent Disks",
        df: "Redundant Array of Independent Disks, combines multiple drives to improve speed and/or provide fault tolerance depending on RAID level." },
      { ac: "RPM",
        ex: "Revolutions Per Minute",
        df: "A measurement of rotational speed that indicates how many full turns a mechanical device (like a hard drive spindle or cooling fan) makes each minute." },
      { ac: "SAN",
        ex: "Storage Area Network",
        df: "Storage Area Network, dedicated high-speed network that provides block-level storage to servers." },
      { ac: "SAS",
        ex: "Serial Attached SCSI [Small Computer System Interface]",
        df: "Serial Attached SCSI, point-to-point serial protocol for connecting enterprise HDDs/SSDs with high throughput and reliability." },
      { ac: "SATA",
        ex: "Serial Advanced Technology Attachment",
        df: "Serial ATA, interface for connecting HDDs/SSDs/ODDs to the motherboard; supports hot-swap and high-speed transfers." },
      { ac: "SCSI",
        ex: "Small Computer System Interface",
        df: "Small Computer System Interface, standard for connecting and transferring data between computers and peripherals (legacy/enterprise)." },
      { ac: "SD",
        ex: "Secure Digital",
        df: "Secure Digital, family of removable flash memory cards used in cameras, phones, and IoT devices." },
      { ac: "SDS",
        ex: "Software Defined Storage",
        df: "Storage architecture where storage resources are managed and controlled by software rather than hardware. It allows flexibility, scalability, and centralized management in cloud and data center environments." },
      { ac: "S.M.A.R.T",
        ex: "Self-monitoring Analysis and Reporting Technology",
        df: "A monitoring system built into hard drives and SSDs that detects and reports on drive health to predict potential failures." },
      { ac: "SSD",
        ex: "Solid-state Drive",
        df: "Solid-State Drive, flash-based storage with fast read/write speeds and no moving parts." },
      ] },
    { name: "WIRELESS & MOBILE",
      items: [
      { ac: "AP",
        ex: "Access Point",
        df: "Wireless access point; bridges Wi-Fi clients to the wired LAN." },
      { ac: "BYOD",
        ex: "Bring Your Own Device",
        df: "Practice of employees using personal devices for work; requires strong security controls and policy." },
      { ac: "eSIM",
        ex: "Embedded Subscriber Identity Module",
        df: "Built-in digital SIM inside a mobile device that allows you to activate cellular service without inserting a physical SIM card. Common in newer smartphones and IoT devices" },
      { ac: "GPS",
        ex: "Global Positioning System",
        df: "Global Positioning System, satellite-based navigation and time source used for location services and accurate timekeeping." },
      { ac: "LTE",
        ex: "Long-Term Evolution",
        df: "A 4G cellular data standard that provides high-speed wireless Internet over mobile networks." },
      { ac: "MDM",
        ex: "Mobile Device Management",
        df: "Software suite that centrally manages and secures mobile devices (enforce passcodes, push configs, remote wipe)." },
      { ac: "RFID",
        ex: "Radio-frequency Identification",
        df: "Radio-Frequency Identification, uses radio waves and tags to identify and track items (badges, inventory) without a line of sight." },
      { ac: "SIM",
        ex: "Subscriber Identity Module",
        df: "Subscriber Identity Module, smart card in mobile devices that stores carrier identity and network credentials." },
      { ac: "SMS",
        ex: "Short Message Service",
        df: "Standard text-messaging technology used to send and receive short messages on mobile phones." },
      { ac: "SSID",
        ex: "Service Set Identifier",
        df: "Service Set Identifier, the broadcast name of a Wi-Fi network that clients see when connecting." },
      { ac: "TKIP",
        ex: "Temporal Key Integrity Protocol",
        df: "An older Wi-Fi encryption protocol used with WPA that dynamically changes encryption keys to improve wireless security." },
      { ac: "WAP",
        ex: "Wireless Access Point",
        df: "A wireless access point that connects wireless devices to a wired network, enabling Wi-Fi connectivity." },
      { ac: "WEP",
        ex: "Wired Equivalency Privacy",
        df: "Outdated and insecure wireless encryption standard used to protect Wi-Fi networks. It has known vulnerabilities and should not be used, replaced by WPA2/WPA3." },
      { ac: "WISP",
        ex: "Wireless Internet Service Provider",
        df: "An ISP that delivers internet access via wireless (often fixed wireless) links." },
      { ac: "WLAN",
        ex: "Wireless LAN [Local Area Network]",
        df: "A local area network that uses wireless communication to connect devices within a limited area like a home or office." },
      { ac: "WPA",
        ex: "Wi-Fi Protected Access",
        df: "A Wi-Fi security protocol that improves encryption and authentication compared to the older WEP standard." },
      { ac: "WWAN",
        ex: "Wireless Wide Area Network",
        df: "Cellular-based data networking (e.g., LTE/5G) for wide-area connectivity beyond local Wi-Fi." },
      ] },
    { name: "IDENTITY & ACCESS",
      items: [
      { ac: "AAA",
        ex: "Authentication, Authorization, and Accounting",
        df: "Security framework that controls access by verifying identity (authentication), deciding permissions (authorization), and tracking activity (accounting)." },
      { ac: "ACL",
        ex: "Access Control List",
        df: "A rule list on devices or file systems that allows or denies specific traffic or user actions." },
      { ac: "CAC",
        ex: "Calling-card Authorization Computer",
        df: "Common Access Card: a smart ID card providing strong authentication, commonly used in government/DoD environments." },
      { ac: "IAM",
        ex: "Identity and Access Management",
        df: "Identity and Access Management, policies and tools to authenticate users and control what resources they can access." },
      { ac: "MFA",
        ex: "Multifactor Authentication",
        df: "An authentication method requiring two or more verification factors (e.g., password + app code or token)." },
      { ac: "NAC",
        ex: "Network Access Control",
        df: "Network Access Control, checks a device's security posture and controls whether it can join the network." },
      { ac: "OTP",
        ex: "One-time Password (or Passcode)",
        df: "One-Time Password, single-use code (often via app or SMS) used to verify identity during login." },
      { ac: "PAM",
        ex: "Privileged Access Management",
        df: "Privileged Access Management, controls, monitors, and secures use of administrative or high-risk accounts." },
      { ac: "PIN",
        ex: "Personal Identification Number",
        df: "Personal Identification Number, a short numeric code used to authenticate a user." },
      { ac: "PIV",
        ex: "Personal Identity Verification",
        df: "Personal Identity Verification, U.S. federal smart card standard that stores certificates for authentication." },
      { ac: "RADIUS",
        ex: "Remote Authentication Dial-in User Server",
        df: "Remote Authentication Dial-in User Service, centralized AAA (authentication, authorization, accounting) for network logins and Wi-Fi/VPN access." },
      { ac: "SAML",
        ex: "Security Assertions Markup Language",
        df: "An open standard that enables secure exchange of authentication and authorization data between identity providers and service providers, supporting single sign-on (SSO)." },
      { ac: "SSO",
        ex: "Single Sign-on",
        df: "Single Sign-On, lets a user authenticate once to access multiple apps/services without re-entering credentials." },
      { ac: "TACACS",
        ex: "Terminal Access Controller Access-control System",
        df: "A protocol used to provide centralized authentication, authorization, and accounting for users accessing network devices." },
      { ac: "TOTP",
        ex: "Time-based One-time Password",
        df: "A temporary, time-based password used for multi-factor authentication; it changes every set number of seconds." },
      ] },
    { name: "SECURITY CONTROLS",
      items: [
      { ac: "AES",
        ex: "Advanced Encryption Standard",
        df: "Widely used symmetric-key encryption standard that protects data at rest and in transit (e.g., WPA2/WPA3)." },
      { ac: "DKIM",
        ex: "DomainKeys Identified Mail",
        df: "Email authentication using cryptographic signatures to verify messages weren't altered and are authorized by the sending domain." },
      { ac: "DLP",
        ex: "Data Loss Prevention",
        df: "Tools and policies that prevent sensitive data from leaving the organization (email, web, storage)." },
      { ac: "DMARC",
        ex: "Domain-based Message Authentication, Reporting, and Conformance",
        df: "Email policy telling receivers how to handle messages failing SPF/DKIM and providing domain-owner reporting." },
      { ac: "DRM",
        ex: "Digital Rights Management",
        df: "Technologies that control how digital content can be accessed, copied, or shared." },
      { ac: "EDR",
        ex: "Endpoint Detection and Response",
        df: "Endpoint Detection and Response security that continuously monitors endpoint activity, detects suspicious behavior, and helps contain or remediate threats." },
      { ac: "FRT",
        ex: "Facial Recognition Technology",
        df: "Facial Recognition Technology, biometric tech that identifies or verifies a person using their face (used for device unlock and access control)." },
      { ac: "HSM",
        ex: "Hardware Security Module",
        df: "Hardware Security Module, tamper-resistant device that generates, stores, and uses cryptographic keys securely." },
      { ac: "MDR",
        ex: "Managed Detection and Response",
        df: "A managed security service that provides continuous threat monitoring, detection, and response by a provider." },
      { ac: "SPF",
        ex: "Sender Policy Framework",
        df: "Sender Policy Framework, DNS-based email authentication to verify which mail servers can send for a domain; helps stop spoofing." },
      { ac: "TPM",
        ex: "Trusted Platform Module",
        df: "A tamper-resistant chip on the motherboard that securely stores crypto keys and measures boot integrity (used for BitLocker, secure boot, and device attestation)." },
      { ac: "UTM",
        ex: "Unified Threat Management",
        df: "All-in-one security appliance (often a next-gen firewall) combining functions like firewalling, IDS/IPS, AV, web filtering, and VPN." },
      { ac: "XDR",
        ex: "Extended Detection and Response",
        df: "Security platform that correlates telemetry across endpoints, network, email, and cloud to detect and respond to threats faster." },
      ] },
    { name: "CABLES, PORTS & CONNECTORS",
      items: [
      { ac: "BNC",
        ex: "Bayonet Neill-Concelman",
        df: "Bayonet-style RF coax connector used on older Ethernet and video equipment." },
      { ac: "DB-9",
        ex: "Serial Communications D-Shell Connector, 9 pins",
        df: "9-pin D-sub serial connector often used for RS-232 on legacy PCs and network gear." },
      { ac: "IR",
        ex: "Infrared",
        df: "Infrared, short-range, light-based wireless communication used in remote controls and some proximity sensors." },
      { ac: "LC",
        ex: "Lucent Connector",
        df: "A small form-factor fiber-optic connector that uses a latch; common for high-density network patch panels." },
      { ac: "NFC",
        ex: "Near-field Communication",
        df: "Near Field Communication, very short-range wireless used for tap-to-pay, pairing, and badge access." },
      { ac: "PoE",
        ex: "Power over Ethernet",
        df: "Power over Ethernet, supplies electrical power and data over the same Ethernet cable to devices like APs and cameras." },
      { ac: "RJ11",
        ex: "Registered Jack Function 11",
        df: "Registered Jack 11, 4P2C/6P2C modular connector commonly used for telephone lines." },
      { ac: "RJ45",
        ex: "Registered Jack Function 45",
        df: "Registered Jack 45, 8P8C modular connector typically used for Ethernet network cabling." },
      { ac: "SC",
        ex: "Subscriber Connector",
        df: "Subscriber Connector, push-pull fiber-optic connector with a square body; common in enterprise fiber runs." },
      { ac: "ST",
        ex: "Straight Tip",
        df: "Straight Tip, bayonet-style fiber-optic connector commonly used in older networks and instrumentation." },
      { ac: "USB",
        ex: "Universal Serial Bus",
        df: "A standard interface used to connect peripherals like keyboards, mice, and storage devices to computers." },
      { ac: "USB-C",
        ex: "Universal Serial Bus Type C",
        df: "Reversible USB connector that can carry data, video, and power; supports USB 3.x/4, DisplayPort Alt Mode, and USB Power Delivery." },
      ] },
    { name: "DISPLAYS & VIDEO",
      items: [
      { ac: "DVI",
        ex: "Digital Visual Interface",
        df: "Digital video interface standard for connecting computers to monitors." },
      { ac: "HD",
        ex: "High Definition",
        df: "High Definition, video/display resolution such as 720p/1080p that provides sharper images than standard definition." },
      { ac: "HDMI",
        ex: "High-definition Media Interface",
        df: "High-Definition Multimedia Interface, digital audio/video interface for displays and TVs; carries video and multi-channel audio over one cable." },
      { ac: "IPS",
        ex: "In-plane Switching",
        df: "In-Plane Switching, LCD display panel technology known for better color accuracy and wide viewing angles compared to TN/VA." },
      { ac: "KVM",
        ex: "Keyboard-Video-Mouse",
        df: "A hardware switch or device that lets you control multiple computers using a single keyboard, video display, and mouse." },
      { ac: "LCD",
        ex: "Liquid Crystal Display",
        df: "Flat-panel display technology that uses liquid crystals and a backlight; common in monitors and laptops." },
      { ac: "LED",
        ex: "Light-emitting Diode",
        df: "Light-emitting diode technology used for indicator lights and as a backlight or pixel source in modern displays." },
      { ac: "OLED",
        ex: "Organic Light-emitting Diode",
        df: "Display tech where each pixel emits its own light; offers deep blacks and high contrast." },
      { ac: "RGB",
        ex: "Red-Green-Blue",
        df: "Red-Green-Blue, additive color model used by displays and LEDs to create colors by mixing red, green, and blue light." },
      { ac: "TN",
        ex: "Twisted Nematic",
        df: "A type of LCD panel technology known for fast response times, commonly used in monitors and displays." },
      { ac: "VA",
        ex: "Vertical Alignment",
        df: "LCD panel technology known for high contrast and deep blacks, typically with slower response times than TN/IPS." },
      { ac: "VGA",
        ex: "Video Graphics Array",
        df: "An older analog display connector standard used to connect monitors to computers." },
      ] },
    { name: "FILE SYSTEMS & SHARES",
      items: [
      { ac: "APFS",
        ex: "Apple File System",
        df: "Apple's modern file system with features like snapshots, cloning, and strong encryption." },
      { ac: "CIFS",
        ex: "Common Internet File System",
        df: "File-sharing protocol (early form of SMB) used to access files and printers over a network." },
      { ac: "EFS",
        ex: "Encrypting File System",
        df: "Encrypting File System, a Windows feature that encrypts files/folders on NTFS volumes so only authorized users can read them." },
      { ac: "exFAT",
        ex: "Extended File Allocation Table",
        df: "Extended File Allocation Table, a Microsoft file system optimized for flash drives; supports very large files and is widely compatible across OSes." },
      { ac: "FAT32",
        ex: "32-bit File Allocation Table",
        df: "32-bit File Allocation Table, an older, very compatible file system for removable media; limited to 4 GB per file and 2 TB volumes." },
      { ac: "NTFS",
        ex: "New Technology File System",
        df: "Windows file system that supports permissions, encryption, compression, quotas, and large volumes." },
      { ac: "ReFS",
        ex: "Resilient File System",
        df: "Resilient File System, Microsoft file system with data integrity features, large volume support, and automatic corruption repair." },
      { ac: "SMB",
        ex: "Server Message Block",
        df: "Server Message Block, protocol for Windows file/print sharing and network resource access." },
      { ac: "XFS",
        ex: "Extent File System",
        df: "High-performance, 64-bit journaling file system (commonly on Linux) optimized for very large files and scalability." },
      ] },
    { name: "OPERATING SYSTEMS & TOOLS",
      items: [
      { ac: "GUI",
        ex: "Graphical User Interface",
        df: "User interface that allows interaction with a device using visual elements like windows, icons, buttons, and menus instead of text commands. Examples include Windows and macOS desktops." },
      { ac: "GUID",
        ex: "Globally Unique Identifier",
        df: "Globally Unique Identifier, a 128-bit value used to uniquely identify objects (files, partitions, software components) across systems." },
      { ac: "MMC",
        ex: "Microsoft Management Console",
        df: "Microsoft Management Console, Windows framework that hosts administrative snap-ins (e.g., Device Manager)." },
      { ac: "OS",
        ex: "Operating System",
        df: "Operating System, software that manages hardware and provides services for applications (e.g., Windows, Linux)." },
      { ac: "SQL",
        ex: "Structured Query Language",
        df: "Structured Query Language, language to create, read, update, and delete data in relational databases." },
      { ac: "UAC",
        ex: "User Account Control",
        df: "Windows feature that prompts before allowing administrative actions, reducing the risk of malware or accidental system changes." },
      { ac: "VDI",
        ex: "Virtual Desktop Infrastructure",
        df: "Centralized desktops run on servers and are delivered to users remotely, simplifying management and improving security." },
      { ac: "VM",
        ex: "Virtual Machine",
        df: "A software-emulated computer running its own OS and apps on a host via a hypervisor, isolating workloads." },
      ] },
    { name: "THREATS & FAILURES",
      items: [
      { ac: "BEC",
        ex: "Business Email Compromise",
        df: "Social-engineering scam where attackers impersonate executives to trick staff into sending money or data." },
      { ac: "BSOD",
        ex: "Blue Screen of Death",
        df: "Windows stop error screen indicating a critical system failure requiring reboot and troubleshooting." },
      { ac: "DDOS",
        ex: "Distributed Denial of Service",
        df: "Distributed Denial of Service: a technology or concept used in IT; know what it is and when to use it for the A+ exam." },
      { ac: "DOS",
        ex: "Denial of Service",
        df: "Denial of Service: a technology or concept used in IT; an attack that overwhelms a server, service, or network with a flood of internet traffic from multiple sources." },
      { ac: "PUP",
        ex: "Potentially Unwanted Program",
        df: "Potentially Unwanted Program, software that a user didn't intend to install; often adware or bundled tools." },
      { ac: "XSS",
        ex: "Cross-site Scripting",
        df: "A web attack where malicious scripts are injected into trusted sites; can steal cookies, sessions, or perform actions as the user." },
      ] },
    { name: "CLOUD",
      items: [
      { ac: "FaaS",
        ex: "Function as a Service",
        df: "Cloud computing model where developers run code in response to events without managing servers. Examples include serverless platforms like AWS Lambda, Azure Functions. You only pay when the function runs." },
      { ac: "IaaS",
        ex: "Infrastructure as a Service",
        df: "Infrastructure as a Service, cloud model providing virtual machines, storage, and networking so you don't manage physical hardware." },
      { ac: "PaaS",
        ex: "Platform as a Service",
        df: "Platform as a Service, cloud service that provides runtime, databases, and tools so you deploy apps without managing servers." },
      { ac: "SaaS",
        ex: "Software as a Service",
        df: "A cloud-computing model where applications are hosted online and accessed through a browser rather than installed locally (examples: Microsoft 365, Google Workspace)." },
      { ac: "XaaS",
        ex: "Anything As A Service",
        df: "An umbrella term for cloud-based services delivered over the internet, such as SaaS, PaaS, and IaaS." },
      ] },
    { name: "PRINTERS",
      items: [
      { ac: "ADF",
        ex: "Automatic Document Feeder",
        df: "Printer/scanner feeder that automatically pulls multiple pages for scanning or copying." },
      { ac: "MFP",
        ex: "Multifunction Printer",
        df: "A multi-function printer that combines printing, scanning, copying, and often faxing in one device." },
      { ac: "PCL",
        ex: "Printer Command Language",
        df: "Printer Command Language, page description language (from HP) widely supported by printers." },
      ] },
  ]
};
